# Generated by Django 3.2.5 on 2021-07-03 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bankdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(default=None, max_length=500)),
                ('currency', models.CharField(max_length=100)),
                ('error_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('card_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentmode', models.CharField(max_length=100)),
                ('totalamount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('txndate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bankdetails',
            },
        ),
        migrations.CreateModel(
            name='cancelorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelinfo', models.CharField(max_length=1000)),
                ('order_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('initiatedpay', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.bankdetails')),
            ],
            options={
                'db_table': 'cancelorders',
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantitys', models.IntegerField(default='1')),
                ('title', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('added', models.BooleanField(default=True)),
                ('cust_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccode', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('Userlimit', models.CharField(default='0', max_length=100)),
                ('percentage', models.CharField(default='None', max_length=30)),
                ('add_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('discount', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='desiarmy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('images', models.FileField(blank=True, null=True, upload_to='army_image')),
            ],
            options={
                'db_table': 'desiarmy',
            },
        ),
        migrations.CreateModel(
            name='headingtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'title',
            },
        ),
        migrations.CreateModel(
            name='homepageimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='homepage_image')),
            ],
            options={
                'db_table': 'homepageimg',
            },
        ),
        migrations.CreateModel(
            name='homepageword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'homepageword',
            },
        ),
        migrations.CreateModel(
            name='imagesupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='carouselimage')),
                ('model_name', models.CharField(default='0', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'imageupload',
            },
        ),
        migrations.CreateModel(
            name='Mobilecover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('mobilename', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'arrangementofcover',
            },
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(default=False)),
            ],
            options={
                'db_table': 'pincode',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='None', max_length=500)),
                ('category', models.CharField(max_length=1000)),
                ('model_No', models.CharField(max_length=1000)),
                ('images1', models.FileField(blank=True, null=True, upload_to='profile_image')),
                ('images2', models.FileField(blank=True, null=True, upload_to='profile_image')),
                ('images3', models.FileField(blank=True, null=True, upload_to='profile_image')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.CharField(max_length=500)),
                ('sub_category', models.CharField(max_length=1000)),
                ('weight', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('size', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(blank=True, default='Desi Cover', max_length=100, null=True)),
                ('add_recent', models.BooleanField(default=False)),
                ('avg_rating', models.FloatField(blank=True, default='0', null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Tshirtsize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.CharField(blank=True, max_length=120, null=True)),
                ('Medium', models.CharField(blank=True, max_length=120, null=True)),
                ('large', models.CharField(blank=True, max_length=120, null=True)),
                ('xl', models.CharField(blank=True, max_length=120, null=True)),
                ('xxl', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'tshirtsize',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(default=0)),
                ('running_balance', models.BigIntegerField(default=0)),
                ('information', models.CharField(default='None', max_length=1000)),
                ('typeofmoney', models.CharField(default='credit', max_length=100)),
                ('card_info', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('rating', models.FloatField()),
                ('cust_username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewprod', to='store.products')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='recentarrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
            options={
                'db_table': 'recentarrival',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='tshirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.tshirtsize'),
        ),
        migrations.CreateModel(
            name='placeorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('totalamount', models.IntegerField()),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('paymentmode', models.CharField(max_length=100)),
                ('delivered', models.BooleanField(default=True)),
                ('custdelieverd', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.bankdetails')),
                ('cancelorders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cancelorders')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon')),
                ('cust_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carts')),
            ],
            options={
                'db_table': 'placeorder',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=100)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.carts')),
                ('cust_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='orderawb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb', models.CharField(max_length=100)),
                ('awb_order_id', models.CharField(max_length=10000)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
                ('placeorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.placeorders')),
            ],
            options={
                'db_table': 'orderawb',
            },
        ),
        migrations.CreateModel(
            name='homedesimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
            options={
                'db_table': 'homedesimage',
            },
        ),
        migrations.AddField(
            model_name='carts',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
    ]
