# Generated by Django 2.2.5 on 2019-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('date_of_purchase', models.DateField(auto_now_add=True)),
                ('passw', models.CharField(max_length=50)),
                ('cnf_passw', models.CharField(max_length=50)),
                ('room', models.IntegerField()),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
